name: Deployment 
on:
  push:
    branches:
      - main
      - beta
      - alpha

jobs:
  deploy:
    name: Deploy git tags
    # skip if '[skip ci]' exists in commit message 
    if: ${{ !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
      - name: Install dependencies for building 
        run: npm ci
      - name: Compile 
        run: | 
          npm run build
      - name: Deploy via semantic release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          # version numbers below can be in many forms: M, M.m, M.m.p
          semantic_version: 17
          extra_plugins: |
            @semantic-release/exec@5
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PUSH_TOKEN }}