name: Test

on: [push]

jobs:
  test:
    name: Run tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
      - name: Install dependencies
        run: npm ci             
      - name: Run tests 
        run:  npm run test
      - name: Compile action before testing it 
        run: npm run compile
      # Thanks: https://github.com/actions/typescript-action/blob/b4f07da86601110b682c6f45ff575f5fbd0f8cdf/.github/workflows/test.yml#L18      
      - name: Test Action
        uses: ./ 
        with:
          text: "Sample input text"